# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biosignals.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindows(object):
    def setupUi(self, MainWindows):
        MainWindows.setObjectName("MainWindows")
        MainWindows.resize(1026, 743)
        MainWindows.setStyleSheet("")
        MainWindows.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.windows_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.windows_tabWidget.setObjectName("windows_tabWidget")
        self.principal_tab = QtWidgets.QWidget()
        self.principal_tab.setObjectName("principal_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.principal_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.controlsGroup_verticalLayout = QtWidgets.QVBoxLayout()
        self.controlsGroup_verticalLayout.setObjectName("controlsGroup_verticalLayout")
        self.external_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.external_groupBox.setMinimumSize(QtCore.QSize(260, 80))
        self.external_groupBox.setMaximumSize(QtCore.QSize(260, 80))
        self.external_groupBox.setObjectName("external_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.external_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.external_horizontalLayout = QtWidgets.QHBoxLayout()
        self.external_horizontalLayout.setObjectName("external_horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.external_horizontalLayout.addItem(spacerItem)
        self.btn_user = QtWidgets.QPushButton(self.external_groupBox)
        self.btn_user.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_user.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_user.setObjectName("btn_user")
        self.external_horizontalLayout.addWidget(self.btn_user)
        self.btn_loadScript = QtWidgets.QPushButton(self.external_groupBox)
        self.btn_loadScript.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_loadScript.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_loadScript.setObjectName("btn_loadScript")
        self.external_horizontalLayout.addWidget(self.btn_loadScript)
        spacerItem1 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.external_horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.external_horizontalLayout)
        self.controlsGroup_verticalLayout.addWidget(self.external_groupBox)
        self.connect_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.connect_groupBox.setMinimumSize(QtCore.QSize(260, 120))
        self.connect_groupBox.setMaximumSize(QtCore.QSize(260, 120))
        self.connect_groupBox.setObjectName("connect_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.connect_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.empatica_horizontalLayout = QtWidgets.QHBoxLayout()
        self.empatica_horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.empatica_horizontalLayout.setObjectName("empatica_horizontalLayout")
        self.E4_server_IP_textEdit = QtWidgets.QLineEdit(self.connect_groupBox)
        self.E4_server_IP_textEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.E4_server_IP_textEdit.setObjectName("E4_server_IP_textEdit")
        self.empatica_horizontalLayout.addWidget(self.E4_server_IP_textEdit)
        self.btn_server = QtWidgets.QPushButton(self.connect_groupBox)
        self.btn_server.setMinimumSize(QtCore.QSize(120, 25))
        self.btn_server.setMaximumSize(QtCore.QSize(120, 25))
        self.btn_server.setObjectName("btn_server")
        self.empatica_horizontalLayout.addWidget(self.btn_server)
        self.verticalLayout_4.addLayout(self.empatica_horizontalLayout)
        self.device_horizontalLayout = QtWidgets.QHBoxLayout()
        self.device_horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.device_horizontalLayout.setObjectName("device_horizontalLayout")
        self.device_comboBox = QtWidgets.QComboBox(self.connect_groupBox)
        self.device_comboBox.setEnabled(True)
        self.device_comboBox.setMinimumSize(QtCore.QSize(70, 25))
        self.device_comboBox.setMaximumSize(QtCore.QSize(70, 25))
        self.device_comboBox.setEditable(False)
        self.device_comboBox.setCurrentText("")
        self.device_comboBox.setIconSize(QtCore.QSize(16, 16))
        self.device_comboBox.setObjectName("device_comboBox")
        self.device_horizontalLayout.addWidget(self.device_comboBox)
        self.btn_refresh = QtWidgets.QPushButton(self.connect_groupBox)
        self.btn_refresh.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_refresh.setMaximumSize(QtCore.QSize(70, 25))
        self.btn_refresh.setObjectName("btn_refresh")
        self.device_horizontalLayout.addWidget(self.btn_refresh)
        self.btn_connect = QtWidgets.QPushButton(self.connect_groupBox)
        self.btn_connect.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_connect.setMaximumSize(QtCore.QSize(70, 25))
        self.btn_connect.setObjectName("btn_connect")
        self.device_horizontalLayout.addWidget(self.btn_connect)
        self.verticalLayout_4.addLayout(self.device_horizontalLayout)
        self.controlsGroup_verticalLayout.addWidget(self.connect_groupBox)
        self.controls_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.controls_groupBox.setMinimumSize(QtCore.QSize(260, 100))
        self.controls_groupBox.setMaximumSize(QtCore.QSize(260, 200))
        self.controls_groupBox.setObjectName("controls_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.controls_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.windowsSize_formLayout = QtWidgets.QFormLayout()
        self.windowsSize_formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout.setContentsMargins(6, 6, 6, 6)
        self.windowsSize_formLayout.setSpacing(6)
        self.windowsSize_formLayout.setObjectName("windowsSize_formLayout")
        self.bvpWindowsSize_label = QtWidgets.QLabel(self.controls_groupBox)
        self.bvpWindowsSize_label.setObjectName("bvpWindowsSize_label")
        self.windowsSize_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bvpWindowsSize_label)
        self.bvpWindowsSize_spinBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.bvpWindowsSize_spinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bvpWindowsSize_spinBox.setMinimum(5)
        self.bvpWindowsSize_spinBox.setMaximum(300)
        self.bvpWindowsSize_spinBox.setProperty("value", 12)
        self.bvpWindowsSize_spinBox.setObjectName("bvpWindowsSize_spinBox")
        self.windowsSize_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bvpWindowsSize_spinBox)
        self.gsrWindowsSize_label = QtWidgets.QLabel(self.controls_groupBox)
        self.gsrWindowsSize_label.setObjectName("gsrWindowsSize_label")
        self.windowsSize_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gsrWindowsSize_label)
        self.tmpWindowsSize_spinBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.tmpWindowsSize_spinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tmpWindowsSize_spinBox.setMinimum(5)
        self.tmpWindowsSize_spinBox.setMaximum(300)
        self.tmpWindowsSize_spinBox.setProperty("value", 120)
        self.tmpWindowsSize_spinBox.setObjectName("tmpWindowsSize_spinBox")
        self.windowsSize_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tmpWindowsSize_spinBox)
        self.tmpWindowsSize_label = QtWidgets.QLabel(self.controls_groupBox)
        self.tmpWindowsSize_label.setObjectName("tmpWindowsSize_label")
        self.windowsSize_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tmpWindowsSize_label)
        self.gsrWindowsSize_spinBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.gsrWindowsSize_spinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gsrWindowsSize_spinBox.setMinimum(5)
        self.gsrWindowsSize_spinBox.setMaximum(300)
        self.gsrWindowsSize_spinBox.setProperty("value", 120)
        self.gsrWindowsSize_spinBox.setObjectName("gsrWindowsSize_spinBox")
        self.windowsSize_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gsrWindowsSize_spinBox)
        self.accWindowsSize_label = QtWidgets.QLabel(self.controls_groupBox)
        self.accWindowsSize_label.setObjectName("accWindowsSize_label")
        self.windowsSize_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.accWindowsSize_label)
        self.accWindowsSize_spinBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.accWindowsSize_spinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.accWindowsSize_spinBox.setMinimum(5)
        self.accWindowsSize_spinBox.setMaximum(300)
        self.accWindowsSize_spinBox.setProperty("value", 12)
        self.accWindowsSize_spinBox.setObjectName("accWindowsSize_spinBox")
        self.windowsSize_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.accWindowsSize_spinBox)
        self.verticalLayout_3.addLayout(self.windowsSize_formLayout)
        self.controlsGroup_verticalLayout.addWidget(self.controls_groupBox)
        self.groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.groupBox.setMinimumSize(QtCore.QSize(260, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(260, 100))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 243, 67))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PORT_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.PORT_spinBox.setMinimumSize(QtCore.QSize(70, 25))
        self.PORT_spinBox.setMaximumSize(QtCore.QSize(70, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 42, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.PORT_spinBox.setPalette(palette)
        self.PORT_spinBox.setMinimum(10000)
        self.PORT_spinBox.setMaximum(11000)
        self.PORT_spinBox.setObjectName("PORT_spinBox")
        self.gridLayout_3.addWidget(self.PORT_spinBox, 2, 2, 1, 1)
        self.btn_trigger = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_trigger.setMinimumSize(QtCore.QSize(75, 25))
        self.btn_trigger.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_trigger.setObjectName("btn_trigger")
        self.gridLayout_3.addWidget(self.btn_trigger, 2, 0, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_start.setEnabled(True)
        self.btn_start.setMinimumSize(QtCore.QSize(75, 25))
        self.btn_start.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_start.setObjectName("btn_start")
        self.gridLayout_3.addWidget(self.btn_start, 1, 1, 1, 1)
        self.IP_textEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.IP_textEdit.setMinimumSize(QtCore.QSize(75, 25))
        self.IP_textEdit.setMaximumSize(QtCore.QSize(75, 25))
        self.IP_textEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_textEdit.setObjectName("IP_textEdit")
        self.gridLayout_3.addWidget(self.IP_textEdit, 2, 1, 1, 1)
        self.controlsGroup_verticalLayout.addWidget(self.groupBox)
        self.log_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.log_groupBox.setMinimumSize(QtCore.QSize(260, 30))
        self.log_groupBox.setMaximumSize(QtCore.QSize(260, 16777215))
        self.log_groupBox.setObjectName("log_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.log_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logger = QtWidgets.QPlainTextEdit(self.log_groupBox)
        self.logger.setReadOnly(True)
        self.logger.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logger.setObjectName("logger")
        self.verticalLayout_2.addWidget(self.logger)
        self.controlsGroup_verticalLayout.addWidget(self.log_groupBox)
        self.horizontalLayout_4.addLayout(self.controlsGroup_verticalLayout)
        self.signals_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.signals_groupBox.setObjectName("signals_groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.signals_groupBox)
        self.verticalLayout_6.setContentsMargins(6, 12, 6, 6)
        self.verticalLayout_6.setSpacing(24)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bvp_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bvp_plot.sizePolicy().hasHeightForWidth())
        self.bvp_plot.setSizePolicy(sizePolicy)
        self.bvp_plot.setMinimumSize(QtCore.QSize(300, 100))
        self.bvp_plot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bvp_plot.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(10, 10, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.bvp_plot.setProperty("canvasBackground", brush)
        self.bvp_plot.setObjectName("bvp_plot")
        self.verticalLayout_6.addWidget(self.bvp_plot)
        self.gsr_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gsr_plot.sizePolicy().hasHeightForWidth())
        self.gsr_plot.setSizePolicy(sizePolicy)
        self.gsr_plot.setMinimumSize(QtCore.QSize(300, 100))
        brush = QtGui.QBrush(QtGui.QColor(10, 10, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.gsr_plot.setProperty("canvasBackground", brush)
        self.gsr_plot.setObjectName("gsr_plot")
        self.verticalLayout_6.addWidget(self.gsr_plot)
        self.tmp_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tmp_plot.sizePolicy().hasHeightForWidth())
        self.tmp_plot.setSizePolicy(sizePolicy)
        self.tmp_plot.setMinimumSize(QtCore.QSize(300, 100))
        brush = QtGui.QBrush(QtGui.QColor(10, 10, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.tmp_plot.setProperty("canvasBackground", brush)
        self.tmp_plot.setObjectName("tmp_plot")
        self.verticalLayout_6.addWidget(self.tmp_plot)
        self.acc_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acc_plot.sizePolicy().hasHeightForWidth())
        self.acc_plot.setSizePolicy(sizePolicy)
        self.acc_plot.setMinimumSize(QtCore.QSize(300, 100))
        brush = QtGui.QBrush(QtGui.QColor(10, 10, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.acc_plot.setProperty("canvasBackground", brush)
        self.acc_plot.setObjectName("acc_plot")
        self.verticalLayout_6.addWidget(self.acc_plot)
        self.horizontalLayout_4.addWidget(self.signals_groupBox)
        self.windows_tabWidget.addTab(self.principal_tab, "")
        self.others_tab = QtWidgets.QWidget()
        self.others_tab.setObjectName("others_tab")
        self.windows_tabWidget.addTab(self.others_tab, "")
        self.horizontalLayout_6.addWidget(self.windows_tabWidget)
        MainWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 32))
        self.menubar.setObjectName("menubar")
        MainWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindows)
        self.statusbar.setObjectName("statusbar")
        MainWindows.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindows)
        self.windows_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindows)

    def retranslateUi(self, MainWindows):
        _translate = QtCore.QCoreApplication.translate
        MainWindows.setWindowTitle(_translate("MainWindows", "Biosignals"))
        self.external_groupBox.setTitle(_translate("MainWindows", "External controls"))
        self.btn_user.setText(_translate("MainWindows", "Set Users"))
        self.btn_loadScript.setText(_translate("MainWindows", "Load script"))
        self.connect_groupBox.setTitle(_translate("MainWindows", " Connect to the Empatica device"))
        self.E4_server_IP_textEdit.setText(_translate("MainWindows", "localhost"))
        self.btn_server.setText(_translate("MainWindows", "E4 server link"))
        self.btn_refresh.setText(_translate("MainWindows", "Refresh"))
        self.btn_connect.setText(_translate("MainWindows", "Connect"))
        self.controls_groupBox.setTitle(_translate("MainWindows", "Electrophysiological signals controls"))
        self.bvpWindowsSize_label.setText(_translate("MainWindows", "BVP [seconds]"))
        self.gsrWindowsSize_label.setText(_translate("MainWindows", "GSR [seconds]"))
        self.tmpWindowsSize_label.setText(_translate("MainWindows", "TMP [seconds]"))
        self.accWindowsSize_label.setText(_translate("MainWindows", "ACC [seconds]"))
        self.groupBox.setTitle(_translate("MainWindows", "Recording controls"))
        self.btn_trigger.setText(_translate("MainWindows", "Trigger"))
        self.btn_start.setText(_translate("MainWindows", "Start"))
        self.IP_textEdit.setText(_translate("MainWindows", "localhost"))
        self.log_groupBox.setTitle(_translate("MainWindows", "Log viewer"))
        self.signals_groupBox.setTitle(_translate("MainWindows", "Electrophysiological signals "))
        self.windows_tabWidget.setTabText(self.windows_tabWidget.indexOf(self.principal_tab), _translate("MainWindows", "Principal"))
        self.windows_tabWidget.setTabText(self.windows_tabWidget.indexOf(self.others_tab), _translate("MainWindows", "Others"))

from qwt import QwtPlot

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindows = QtWidgets.QMainWindow()
    ui = Ui_MainWindows()
    ui.setupUi(MainWindows)
    MainWindows.show()
    sys.exit(app.exec_())

